version: '3'
services:

  app:
    image: ghcr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      TZ: '${TZ}'
      PUID: '${PUID}'
      PGID: '${PGID}'
    volumes:
      - /mnt/user/appdata/sonarr:/config
      - /mnt/user/media:/data
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr.entrypoints: 'websecure'
      traefik.http.routers.sonarr.rule: 'Host(`${DOMAIN}`)'
    networks:
      proxy:


networks:
  proxy:
    external: true
