version: '3'
services:

  tweet-forward:
    image: ghcr.io/duckmade/tweet-forward:latest
    restart: unless-stopped
    environment:
      API_KEY: '${API_KEY}'
      API_SECRET: '${API_SECRET}'
      ACCESS_TOKEN: '${ACCESS_TOKEN}'
      ACCESS_SECRET: '${ACCESS_SECRET}'
      FOLLOW: '${FOLLOW}'
      CLIENTS: 'telegram'
      TELEGRAM_CHANNEL: '${TELEGRAM_CHANNEL}'
