version: '3'
services:

  app:
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    ports:
      - 8266:8266
    environment:
      TZ: '${TZ}'
      PUID: '${PUID}'
      PGID: '${PGID}'
      UMASK_SET: '002'
      serverIP: '192.168.1.142'
      serverPort: '8266'
      webUIPort: '8265'
      internalNode: 'false'
    volumes:
      - /mnt/user/appdata/tdarr/server:/app/server
      - /mnt/user/appdata/tdarr/configs:/app/configs
      - /mnt/user/appdata/tdarr/logs:/app/logs
      - /mnt/user/media:/media
      - /tmp/tdarr:/temp
    labels:
      traefik.enable: true
      traefik.http.routers.tdarr.entrypoints: 'websecure'
      traefik.http.routers.tdarr.rule: 'Host(`${DOMAIN}`)'
      traefik.http.services.tdarr.loadbalancer.server.port: '8265'
    networks:
      proxy:


networks:
  proxy:
    external: true
