version: '3'
services:

  app:
    image: ghrc.io/duckmade/graphql-api-server:latest
    restart: unless-stopped
    ports:
      - 4000:4000
    environment:
      PATREON_ID: '${PATREON_ID}'
      PATREON_SECRET: '${PATREON_SECRET}'
      SENDINBLUE_KEY: '${SENDINBLUE_KEY}'
      HOST: '${HOST}'
      ORIGINS: '${ORIGINS}'
    labels:
      traefik.enable: true
      traefik.http.routers.graphql-api-server.entrypoints: 'websecure'
      traefik.http.routers.graphql-api-server.rule: 'Host(`${DOMAIN_PUBLIC}`)'
    networks:
      proxy:


networks:
  proxy:
    external: true