version: '3'
services:

  app:
    image: ghcr.io/duckmade/graphql-api-server:latest
    restart: unless-stopped
    environment:
      PATREON_ID: '${PATREON_ID}'
      PATREON_SECRET: '${PATREON_SECRET}'
      SENDINBLUE_KEY: '${SENDINBLUE_KEY}'
      SMTP_TO_NAME: '${SMTP_TO_NAME}'
      SMTP_TO_EMAIL: '${SMTP_TO_EMAIL}'
      ORIGINS: '${ORIGINS}'
    labels:
      traefik.enable: true
      traefik.http.routers.graphql-api-server.entrypoints: 'websecure'
      traefik.http.routers.graphql-api-server.rule: 'Host(`${DOMAIN_PUBLIC}`, `${DOMAIN}`)'
    networks:
      proxy:


networks:
  proxy:
    external: true