version: '3'
services:

  app:
    image: ghcr.io/linuxserver/prowlarr:develop
    restart: unless-stopped
    environment:
      TZ: '${TZ}'
      PUID: '${PUID}'
      PGID: '${PGID}'
    volumes:
      - /mnt/user/appdata/prowlarr:/config
    labels:
      traefik.enable: true
      traefik.http.routers.prowlarr.entrypoints: 'websecure'
      traefik.http.routers.prowlarr.rule: 'Host(`${DOMAIN}`)'
    networks:
      proxy:


networks:
  proxy:
    external: true
