version: '3'
services:
  app:
    image: ghcr.io/linuxserver/jellyfin:latest
    hostname: '${JELLYFIN_HOSTNAME}'
    restart: unless-stopped
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    environment:
      PUID: '0'
      PGID: '0'
      TZ: '${JELLYFIN_TZ}'
      DOCKER_MODS: 'linuxserver/mods:jellyfin-amd'
    volumes:
      - /mnt/user/appdata/jellyfin:/config
      - /mnt/user/data/media:/data/media
      - /tmp/jellyfin:/transcodes
    devices:
      - /dev/dri:/dev/dri
    networks:
      br0:
        ipv4_address: '${JELLYFIN_BR0_IP}'
  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    restart: unless-stopped
    ports:
      - 7878:7878
    environment:
      PUID: '0'
      PGID: '0'
      TZ: '${JELLYFIN_TZ}'
    volumes:
      - /mnt/user/appdata/radarr:/config
      - /mnt/user/data:/data
  lidarr:
    image: ghcr.io/linuxserver/lidarr:latest
    restart: unless-stopped
    ports:
      - 8686:8686
    environment:
      PUID: '0'
      PGID: '0'
      TZ: '${JELLYFIN_TZ}'
    volumes:
      - /mnt/user/appdata/lidarr:/config
      - /mnt/user/data:/data
  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      PUID: '0'
      PGID: '0'
      TZ: '${JELLYFIN_TZ}'
    volumes:
      - /mnt/user/appdata/sonarr:/config
      - /mnt/user/data:/data
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    restart: unless-stopped
    ports:
      - 9696:9696
    environment:
      PUID: '0'
      PGID: '0'
      TZ: '${JELLYFIN_TZ}'
    volumes:
      - /mnt/user/appdata/prowlarr:/config
  transmission:
    image: ghcr.io/linuxserver/transmission:latest
    restart: unless-stopped
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    environment:
      TZ: '${JELLYFIN_TZ}'
      PUID: '0'
      PGID: '0'
    volumes:
      - /mnt/user/appdata/transmission:/config
      - /mnt/user/data/torrents:/data/torrents
      - /mnt/user/data/torrents:/downloads
      - /mnt/user/data/torrents/watch:/watch
networks:
  br0:
    external: true
